version: '3'
services:

  redis:
    image: redis
    hostname: "redis"
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=F416S45DF65SD4F6
      - REDIS_PORT=6379
    volumes:
      - D:/backend/redis/redis.config:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]
    networks:
      - redis-net

  minio:
    image: minio/minio
    hostname: "minio"
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ACCESS_KEY: yylui
      MINIO_SECRET_KEY: F416S45DF65SD4F6
    volumes:
      - D:/backend/minIO:/data
    command: server /data --console-address ":9090"
    restart: always

  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 840702870217
      MYSQL_DATABASE: backend
      MYSQL_USER: yylui
      MYSQL_PASSWORD: 840702870217
    volumes:
      - D:/backend/mariadb:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mariadb

networks:
  redis-net: